language: python
python:
  - "2.6"
  - "2.7"
  - "3.2"
env:
  - DJANGO=1.7.9
  - DJANGO=1.8.2
install:
  - pip install -q Django==$DJANGO --use-mirrors
script:
  - PYTHONPATH=$PYTHONPATH:$PWD django-admin.py test oidc_provider --settings=oidc_provider.tests.test_settings