language: python
python:
  - "2.7"
  - "3.4"
  - "3.5"
env:
  - DJANGO=1.7
  - DJANGO=1.8
  - DJANGO=1.9
matrix:
  exclude:
    - python: "3.5"
      env: DJANGO=1.7
install:
  - pip install -q django==$DJANGO
  - pip install -e .
script:
  - PYTHONPATH=$PYTHONPATH:$PWD django-admin.py test oidc_provider --settings=oidc_provider.tests.app.settings
